# Generated by Django 3.2.8 on 2022-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='updateprofile',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
